/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AcademicRouteImport } from './routes/academic'
import { Route as AdmissionRouteImport } from './routes/admission'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as MediaRouteImport } from './routes/media'
import { Route as NewsRouteImport } from './routes/news'
import { Route as StaffRouteImport } from './routes/staff'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicRoute = AcademicRouteImport.update({
  id: '/academic',
  path: '/academic',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionRoute = AdmissionRouteImport.update({
  id: '/admission',
  path: '/admission',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academic': typeof AcademicRoute
  '/admission': typeof AdmissionRoute
  '/contact': typeof ContactRoute
  '/media': typeof MediaRoute
  '/news': typeof NewsRoute
  '/staff': typeof StaffRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academic': typeof AcademicRoute
  '/admission': typeof AdmissionRoute
  '/contact': typeof ContactRoute
  '/media': typeof MediaRoute
  '/news': typeof NewsRoute
  '/staff': typeof StaffRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academic': typeof AcademicRoute
  '/admission': typeof AdmissionRoute
  '/contact': typeof ContactRoute
  '/media': typeof MediaRoute
  '/news': typeof NewsRoute
  '/staff': typeof StaffRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/academic'
    | '/admission'
    | '/contact'
    | '/media'
    | '/news'
    | '/staff'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/academic'
    | '/admission'
    | '/contact'
    | '/media'
    | '/news'
    | '/staff'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/academic'
    | '/admission'
    | '/contact'
    | '/media'
    | '/news'
    | '/staff'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AcademicRoute: typeof AcademicRoute
  AdmissionRoute: typeof AdmissionRoute
  ContactRoute: typeof ContactRoute
  MediaRoute: typeof MediaRoute
  NewsRoute: typeof NewsRoute
  StaffRoute: typeof StaffRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic': {
      id: '/academic'
      path: '/academic'
      fullPath: '/academic'
      preLoaderRoute: typeof AcademicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admission': {
      id: '/admission'
      path: '/admission'
      fullPath: '/admission'
      preLoaderRoute: typeof AdmissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AcademicRoute: AcademicRoute,
  AdmissionRoute: AdmissionRoute,
  ContactRoute: ContactRoute,
  MediaRoute: MediaRoute,
  NewsRoute: NewsRoute,
  StaffRoute: StaffRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
