/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AcademicRouteImport } from './routes/academic'
import { Route as AdmissionRouteImport } from './routes/admission'
import { Route as ArtLiteratureRouteImport } from './routes/art-literature'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as LanguageDoorRouteImport } from './routes/language-door'
import { Route as MediaRouteImport } from './routes/media'
import { Route as NewsRouteImport } from './routes/news'
import { Route as SsfDawaRouteImport } from './routes/ssf-dawa'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as ApiPublicMediaSplatRouteImport } from './routes/api/public/media/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicRoute = AcademicRouteImport.update({
  id: '/academic',
  path: '/academic',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionRoute = AdmissionRouteImport.update({
  id: '/admission',
  path: '/admission',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtLiteratureRoute = ArtLiteratureRouteImport.update({
  id: '/art-literature',
  path: '/art-literature',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const LanguageDoorRoute = LanguageDoorRouteImport.update({
  id: '/language-door',
  path: '/language-door',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const SsfDawaRoute = SsfDawaRouteImport.update({
  id: '/ssf-dawa',
  path: '/ssf-dawa',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMediaSplatRoute = ApiPublicMediaSplatRouteImport.update({
  id: '/api/public/media/$',
  path: '/api/public/media/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academic': typeof AcademicRoute
  '/admission': typeof AdmissionRoute
  '/art-literature': typeof ArtLiteratureRoute
  '/contact': typeof ContactRoute
  '/language-door': typeof LanguageDoorRoute
  '/media': typeof MediaRoute
  '/news': typeof NewsRoute
  '/ssf-dawa': typeof SsfDawaRoute
  '/staff': typeof StaffRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academic': typeof AcademicRoute
  '/admission': typeof AdmissionRoute
  '/art-literature': typeof ArtLiteratureRoute
  '/contact': typeof ContactRoute
  '/language-door': typeof LanguageDoorRoute
  '/media': typeof MediaRoute
  '/news': typeof NewsRoute
  '/ssf-dawa': typeof SsfDawaRoute
  '/staff': typeof StaffRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academic': typeof AcademicRoute
  '/admission': typeof AdmissionRoute
  '/art-literature': typeof ArtLiteratureRoute
  '/contact': typeof ContactRoute
  '/language-door': typeof LanguageDoorRoute
  '/media': typeof MediaRoute
  '/news': typeof NewsRoute
  '/ssf-dawa': typeof SsfDawaRoute
  '/staff': typeof StaffRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/academic'
    | '/admission'
    | '/art-literature'
    | '/contact'
    | '/language-door'
    | '/media'
    | '/news'
    | '/ssf-dawa'
    | '/staff'
    | '/api/public/media/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/academic'
    | '/admission'
    | '/art-literature'
    | '/contact'
    | '/language-door'
    | '/media'
    | '/news'
    | '/ssf-dawa'
    | '/staff'
    | '/api/public/media/$'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/academic'
    | '/admission'
    | '/art-literature'
    | '/contact'
    | '/language-door'
    | '/media'
    | '/news'
    | '/ssf-dawa'
    | '/staff'
    | '/api/public/media/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AcademicRoute: typeof AcademicRoute
  AdmissionRoute: typeof AdmissionRoute
  ArtLiteratureRoute: typeof ArtLiteratureRoute
  ContactRoute: typeof ContactRoute
  LanguageDoorRoute: typeof LanguageDoorRoute
  MediaRoute: typeof MediaRoute
  NewsRoute: typeof NewsRoute
  SsfDawaRoute: typeof SsfDawaRoute
  StaffRoute: typeof StaffRoute
  ApiPublicMediaSplatRoute: typeof ApiPublicMediaSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic': {
      id: '/academic'
      path: '/academic'
      fullPath: '/academic'
      preLoaderRoute: typeof AcademicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admission': {
      id: '/admission'
      path: '/admission'
      fullPath: '/admission'
      preLoaderRoute: typeof AdmissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/art-literature': {
      id: '/art-literature'
      path: '/art-literature'
      fullPath: '/art-literature'
      preLoaderRoute: typeof ArtLiteratureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/language-door': {
      id: '/language-door'
      path: '/language-door'
      fullPath: '/language-door'
      preLoaderRoute: typeof LanguageDoorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ssf-dawa': {
      id: '/ssf-dawa'
      path: '/ssf-dawa'
      fullPath: '/ssf-dawa'
      preLoaderRoute: typeof SsfDawaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/media/$': {
      id: '/api/public/media/$'
      path: '/api/public/media/$'
      fullPath: '/api/public/media/$'
      preLoaderRoute: typeof ApiPublicMediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AcademicRoute: AcademicRoute,
  AdmissionRoute: AdmissionRoute,
  ArtLiteratureRoute: ArtLiteratureRoute,
  ContactRoute: ContactRoute,
  LanguageDoorRoute: LanguageDoorRoute,
  MediaRoute: MediaRoute,
  NewsRoute: NewsRoute,
  SsfDawaRoute: SsfDawaRoute,
  StaffRoute: StaffRoute,
  ApiPublicMediaSplatRoute: ApiPublicMediaSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
